<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ADOE-20150303CS" ignored="0" name="Default test" tests="17" failures="1" timestamp="07 十一月 2018 05:22:08 GMT" time="4.775" errors="0">
  <testcase name="f" time="1.48" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.172" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.14" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.125" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.125" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.125" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.141" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.156" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.125" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.203" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.172" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.141" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.156" classname="com.yy.test.NewTest"/>
  <testcase name="f" time="0.14" classname="com.yy.test.NewTest"/>
  <testcase name="test1" time="0.0" classname="com.yy.test.NewTest"/>
  <testcase name="test2" time="0.0" classname="com.yy.test.NewTest"/>
  <testcase name="test3" time="0.016" classname="com.yy.test.NewTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.yy.test.NewTest.test3(NewTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- Default test -->
